# Dynamic Workflow Configuration
# Customize steps, approval gates, and instructions for your project

name: default
description: Standard development workflow with approval gates

steps:
  - name: plan
    needs_approval: true
    allows_iteration: true
    approval_prompt: |
      Review the implementation plan. Does this approach look correct?
      - /workflow-approve to proceed to defining criteria
      - /workflow-iterate <feedback> to request changes
    instructions: |
      Explore the codebase and design your approach:
      1. Search for relevant files and understand the existing code
      2. Identify what needs to change
      3. Design your implementation approach
      4. **Include ASCII art or Mermaid diagrams** to visualize architecture
      5. Define verification criteria (tests to run, behavior to check)

      When done:
      - Save plan with workflow_set_plan()
      - Update summary: workflow_set_artifact("summary", {goal, status, completed, current, remaining})
      - Call workflow_next() and STOP AND WAIT for user approval.

  - name: criteria
    needs_approval: true
    allows_iteration: true
    approval_prompt: |
      Review the completion criteria. Are these the right things to verify?
      - /workflow-approve to proceed to implementation
      - /workflow-iterate <feedback> to adjust criteria
    instructions: |
      Define specific, measurable completion criteria:
      1. Based on the approved plan, list what must be verified
      2. Include tests to run, behavior to check, edge cases
      3. Use workflow_set_criteria to record the criteria

      When done:
      - Save criteria with workflow_set_criteria()
      - Update summary artifact with progress
      - Call workflow_next() and STOP AND WAIT for user approval.

  - name: execute
    needs_approval: false
    allows_iteration: true
    instructions: |
      Implement the changes according to your plan:
      1. Make the necessary code changes
      2. Follow existing code patterns and style
      3. Keep changes focused and minimal
      4. Don't introduce unrelated changes

      When done, update summary artifact and move to verify.

  - name: verify
    needs_approval: false
    allows_iteration: true
    instructions: |
      Verify all criteria are met:
      1. Run the tests/checks defined in verification criteria
      2. Confirm each criterion passes
      3. Fix any issues found

      When ALL criteria pass, update summary artifact and proceed.

  - name: pr
    needs_approval: false
    allows_iteration: false
    instructions: |
      Create a pull request:
      1. Create a descriptive PR with summary and test plan
      2. Call workflow_set_pr(pr_number, pr_url) to track the PR
      3. Call workflow_next() to move to review step

  - name: review
    needs_approval: true
    allows_iteration: true
    approval_prompt: |
      PR review complete. Ready to merge?
      - /workflow-approve to complete the workflow
      - /workflow-iterate <feedback> to request more changes
    instructions: |
      Monitor PR for review comments:
      1. Run `gh pr view <pr_number> --comments` to get comment count
      2. Call workflow_check_pr(comment_count) to check status
      3. If action is "address_comments" - address the feedback
      4. If action is "wait" - wait the suggested time, then check again
      5. If action is "ready_for_approval" - call workflow_next()

      STOP AND WAIT for user approval after calling workflow_next().

  - name: complete
    needs_approval: false
    allows_iteration: false
    instructions: |
      Workflow complete. Summarize what was accomplished.
