# Dynamic Workflow Configuration
# Customize steps, approval gates, and instructions for your project

name: default
description: Standard development workflow with approval gates

steps:
  - name: plan
    needs_approval: true
    allows_iteration: true
    approval_prompt: |
      Review the implementation plan. Does this approach look correct?
      - /workflow-approve to proceed to defining criteria
      - /workflow-iterate <feedback> to request changes
    instructions: |
      Explore the codebase and design your approach:
      1. Search for relevant files and understand the existing code
      2. Identify what needs to change
      3. Design your implementation approach
      4. **Include ASCII art or Mermaid diagrams** to visualize architecture
      5. Define verification criteria (tests to run, behavior to check)

      When done:
      - Save plan with workflow_set_plan()
      - Update summary: workflow_set_artifact("summary", {goal, status, completed, current, remaining})
      - Call workflow_next() and STOP AND WAIT for user approval.

  - name: criteria
    needs_approval: true
    allows_iteration: true
    approval_prompt: |
      Review the completion criteria. Are these the right things to verify?
      - /workflow-approve to proceed to implementation
      - /workflow-iterate <feedback> to adjust criteria
    instructions: |
      Define verification criteria based on project context:
      1. Read relevant files first (README, docs, tests, related code)
      2. Based on plan + context, define acceptance criteria
      3. Keep to 5-8 high-level checks (not granular test cases)
      4. Use markdown checkboxes: "- [ ] Criteria item"

      When done:
      - Save criteria with workflow_set_criteria()
      - Update summary artifact with progress
      - Call workflow_next() and STOP AND WAIT for user approval.

  - name: execute
    needs_approval: false
    allows_iteration: true
    instructions: |
      Implement the changes according to your plan:
      1. Make the necessary code changes
      2. Follow existing code patterns and style
      3. Keep changes focused and minimal
      4. Don't introduce unrelated changes

      When done, update summary artifact and move to verify.

  - name: verify
    needs_approval: false
    allows_iteration: true
    instructions: |
      Verify all criteria are met:
      1. Run the tests/checks defined in verification criteria
      2. Confirm each criterion passes
      3. Fix any issues found

      When ALL criteria pass, update summary artifact and proceed.

  - name: pr
    needs_approval: false
    allows_iteration: false
    instructions: |
      Create a pull request:
      1. Create PR with `gh pr create` (include summary and test plan)
      2. Extract PR number and URL from output
      3. Call workflow_set_pr(pr_number, pr_url) to track
      4. **Show the PR link to user** so they can see it
      5. Update summary artifact
      6. Call workflow_next() to start review monitoring

  - name: review
    needs_approval: false
    allows_iteration: true
    instructions: |
      Monitor PR for review comments in a loop:
      1. Run `gh pr view <pr_number> --comments --json comments` to get comments
      2. Call workflow_check_pr(comment_count) to check status
      3. Based on action:
         - "address_comments" → address feedback, update summary, loop back to 1
         - "wait" → wait 1 minute, loop back to 1
         - "ready_for_human_review" → call workflow_next() to request human approval

      Stops after 5 mins of no new comments.

  - name: human_review
    needs_approval: true
    allows_iteration: false
    approval_prompt: |
      PR is ready for your review. All automated checks passed.
      Take a look and say "looks good" when ready to complete.
    instructions: |
      Notify user the PR is ready for their review:
      - Show PR link
      - Summarize what was implemented
      - Note any comments that were addressed

      STOP AND WAIT for user to review and approve.

  - name: complete
    needs_approval: false
    allows_iteration: false
    instructions: |
      Workflow complete. Summarize what was accomplished.
